'use client'

import React, { useState, useEffect, useMemo, useCallback } from 'react'
import { notFound, useRouter } from 'next/navigation'
import { AlertCircle } from 'lucide-react'
import axios from 'axios'
import AddShow from '@/components/addShow'
import ThemeRunner from '@/components/ThemeRunner'
import { useStore } from '@/Hook/store-provider'

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:7000'

/* ─── Types ─────────────────────────────────────────── */
interface VariantAttributeEntry {
  attrId: string; attrName: string; displayMode: 'color' | 'image' | 'text'; value: string
}
interface VariantDetail {
  id: number; name: VariantAttributeEntry[]; price: number; stock: number; autoGenerate: boolean
}
interface Wilaya {
  id: string; name: string; ar_name: string; livraisonHome: number; livraisonOfice: number
}
interface Commune { id: string; name: string; ar_name: string; wilayaId: string }

function variantMatches(detail: VariantDetail, selected: Record<string, string>) {
  return Object.entries(selected).every(([attrName, val]) =>
    detail.name.some(e => e.attrName === attrName && e.value === val),
  )
}

const getWilayas = async (userId: string): Promise<Wilaya[]> => {
  try {
    const { data } = await axios.get(`${API_URL}/shipping/public/get-shipping/${userId}`)
    return data || []
  } catch { return [] }
}

const getCommunes = async (wilayaId: string): Promise<Commune[]> => {
  try {
    const { data } = await axios.get(`${API_URL}/shipping/get-communes/${wilayaId}`)
    return data || []
  } catch { return [] }
}

/* ── Component ── */
export default function ProductClient({
  product,
  store,
  domain,
}: {
  product: any
  store: any
  domain: string
}) {
  const { theme: contextThemeSlug } = useStore()
  const router = useRouter()

  const [selectedImage, setSelectedImage]   = useState(0)
  const [selectedOffer, setSelectedOffer]   = useState<string | null>(product.offers?.[0]?.id ?? null)
  const [selectedVariants, setSelectedVariants] = useState<Record<string, string>>({})
  const [isWishlisted, setIsWishlisted]     = useState(false)
  const [wilayas, setWilayas]               = useState<Wilaya[]>([])
  const [communes, setCommunes]             = useState<Commune[]>([])
  const [loadingCommunes, setLoadingCommunes] = useState(false)
  const [formErrors, setFormErrors]         = useState<Record<string, string>>({})
  const [submitting, setSubmitting]         = useState(false)
  const [formData, setFormData] = useState({
    customerId: '', customerName: '', customerPhone: '',
    customerWelaya: '', customerCommune: '',
    quantity: 1, typeLivraison: 'home' as 'home' | 'office',
  })

  const slug     = contextThemeSlug || store?.theme?.slug || 'default'
  const bundleUrl = `/api/themes/${slug}`

  /* ── Init ── */
  useEffect(() => {
    const id = localStorage.getItem('customerId')
    if (id) setFormData(p => ({ ...p, customerId: id }))
    const wishlist = JSON.parse(localStorage.getItem('wishlist') || '[]')
    setIsWishlisted(wishlist.includes(product.id))
  }, [product.id])

  useEffect(() => {
    if (product?.store?.userId) getWilayas(product.store.userId).then(setWilayas)
  }, [product?.store?.userId])

  useEffect(() => {
    if (!formData.customerWelaya) { setCommunes([]); return }
    setLoadingCommunes(true)
    getCommunes(formData.customerWelaya).then(d => { setCommunes(d); setLoadingCommunes(false) })
  }, [formData.customerWelaya])

  /* ── Pixel tracking ── */
  useEffect(() => {
    if (typeof window === 'undefined') return
    const price = getFinalPrice()
    if ((window as any).fbq)
      (window as any).fbq('track', 'ViewContent', { content_name: product.name, content_ids: [product.id], content_type: 'product', value: price, currency: 'DZD' })
    if ((window as any).ttq)
      (window as any).ttq.track('ViewContent', { contents: [{ content_id: product.id, content_name: product.name, price }], value: price, currency: 'DZD' })
    if ((window as any).gtag)
      (window as any).gtag('event', 'view_item', { currency: 'DZD', value: price, items: [{ item_id: product.id, item_name: product.name }] })
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  /* ── Business logic ── */
  const selectedWilayaData = useMemo(() =>
    wilayas.find(w => String(w.id) === String(formData.customerWelaya)),
    [wilayas, formData.customerWelaya],
  )

  const hasOnlyAutoGeneratedVariants = useCallback(() =>
    !!product.variantDetails?.length && product.variantDetails.every((v: VariantDetail) => v.autoGenerate),
    [product.variantDetails],
  )

  const isInStock = useCallback(() => {
    if (hasOnlyAutoGeneratedVariants()) return true
    if (!product.variantDetails?.length) return (product.stock || 0) > 0
    if (Object.keys(selectedVariants).length > 0) {
      const match = product.variantDetails.find((v: VariantDetail) => variantMatches(v, selectedVariants))
      if (match) return match.autoGenerate || match.stock > 0
    }
    return product.variantDetails.some((v: VariantDetail) => v.autoGenerate || v.stock > 0)
  }, [product, selectedVariants, hasOnlyAutoGeneratedVariants])

  const handleVariantSelection = useCallback((attrName: string, value: string) => {
    setSelectedVariants(prev => {
      const next = { ...prev }
      if (next[attrName] === value) delete next[attrName]
      else next[attrName] = value
      return next
    })
  }, [])

  const getFinalPrice = useCallback(() => {
    const base = typeof product.price === 'string' ? parseFloat(product.price) : product.price
    const offer = product.offers?.find((o: any) => o.id === selectedOffer)
    if (offer) return offer.price
    if (product.variantDetails?.length && Object.keys(selectedVariants).length > 0) {
      const match = product.variantDetails.find((v: VariantDetail) => variantMatches(v, selectedVariants))
      if (match && match.price !== -1) return match.price
    }
    return base
  }, [product, selectedVariants, selectedOffer])

  const getPriceLivraison = useCallback(() =>
    !selectedWilayaData ? 0 :
      formData.typeLivraison === 'home' ? selectedWilayaData.livraisonHome : selectedWilayaData.livraisonOfice,
    [selectedWilayaData, formData.typeLivraison],
  )

  const getVariantDetailId = useCallback(() => {
    if (!product.variantDetails?.length || !Object.keys(selectedVariants).length) return undefined
    return product.variantDetails.find((v: VariantDetail) => variantMatches(v, selectedVariants))?.id
  }, [product.variantDetails, selectedVariants])

  const getTotalPrice = useCallback(() =>
    getFinalPrice() * formData.quantity + +getPriceLivraison(),
    [getFinalPrice, formData.quantity, getPriceLivraison],
  )

  const validateForm = useCallback(() => {
    const errors: Record<string, string> = {}
    if (!formData.customerName.trim() || formData.customerName.length < 3)
      errors.customerName = 'الاسم الكامل مطلوب (3 أحرف على الأقل)'
    if (!formData.customerPhone.trim() || !/^(0|\+213)[5-7][0-9]{8}$/.test(formData.customerPhone.replace(/\s/g, '')))
      errors.customerPhone = 'رقم هاتف جزائري صحيح مطلوب (مثال: 0550123456)'
    if (!formData.customerWelaya) errors.customerWelaya = 'اختر الولاية'
    if (!formData.customerCommune) errors.customerCommune = 'اختر البلدية'
    if (formData.quantity < 1) errors.quantity = 'الكمية يجب أن تكون 1 على الأقل'
    setFormErrors(errors)
    return Object.keys(errors).length === 0
  }, [formData])

  const handleShare = async () => {
    const url = window.location.href
    try {
      if (navigator.share) await navigator.share({ title: product.name, url })
      else { await navigator.clipboard.writeText(url) }
    } catch {}
  }

  const toggleWishlist = () => {
    const wishlist = JSON.parse(localStorage.getItem('wishlist') || '[]')
    const next = isWishlisted
      ? wishlist.filter((id: string) => id !== product.id)
      : [...wishlist, product.id]
    localStorage.setItem('wishlist', JSON.stringify(next))
    setIsWishlisted(!isWishlisted)
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (!validateForm()) return
    setSubmitting(true)
    try {
      const res = await axios.post(`${API_URL}/orders`, {
        productId: product.id,
        variantDetailId: getVariantDetailId(),
        domain,
        offerId: selectedOffer ?? undefined,
        quantity: formData.quantity,
        totalPrice: getTotalPrice(),
        typeShip: formData.typeLivraison,
        priceShip: getPriceLivraison(),
        customerId: formData.customerId,
        customerName: formData.customerName,
        customerPhone: formData.customerPhone,
        customerWilayaId: formData.customerWelaya,
        customerCommuneId: formData.customerCommune,
      })

      if (res.status === 200 || res.status === 201) {
        localStorage.setItem('last_order', JSON.stringify({
          id: res.data?.order?.id || 'NEW_ORDER',
          total: getTotalPrice(),
          productName: product.name,
        }))
        if ((window as any).gtag)
          (window as any).gtag('event', 'purchase', {
            transaction_id: product.id, value: getTotalPrice(), currency: 'DZD',
            items: [{ item_name: product.name, item_id: product.id, price: getFinalPrice(), quantity: formData.quantity }],
          })
        if (res.data?.customerId) localStorage.setItem('customerId', res.data.customerId)
        router.push(`/success?productId=${product.id}`)
      }
    } catch {
      setFormErrors({ submit: 'حدث خطأ في الاتصال بالخادم، يرجى المحاولة مجددًا' })
    } finally {
      setSubmitting(false)
    }
  }

  // imagesProduct[0] هي الصورة الرئيسية دائماً (نفس القاعدة المعتمدة في الداشبورد)،
  // و productImage مجرد حقل احتياطي قديم — لا نجمعه مع imagesProduct لتفادي تكرار نفس الصورة
  const allImages  = product.imagesProduct?.length
    ? product.imagesProduct.map((i: any) => i.imageUrl)
    : [product.productImage].filter(Boolean) as string[]
  const discount   = (() => {
    if (!product.priceOriginal) return 0
    const o = parseFloat(product.priceOriginal.toString())
    const c = getFinalPrice()
    return o > c ? Math.round(((o - c) / o) * 100) : 0
  })()

  return (
    <>
      <AddShow productId={product.id} />
      <ThemeRunner
        bundleUrl={bundleUrl}
        exportName="Details"
        themeProps={{
          product,
          store,
          domain,
          allImages,
          allAttrs: product.attributes || [],
          finalPrice: getFinalPrice(),
          inStock: isInStock(),
          autoGen: hasOnlyAutoGeneratedVariants(),
          discount,
          selectedVariants,
          selectedOffer,
          isWishlisted,
          formData,
          formErrors,
          submitting,
          wilayas,
          communes,
          loadingCommunes,
          setFormData: (d: any) => setFormData(d),
          setSelectedOffer: (id: any) => setSelectedOffer(id),
          handleVariantSelection,
          handleSubmit,
          handleShare,
          toggleWishlist,
          getTotalPrice,
          getPriceLivraison,
          getFinalPrice,
        }}
      />
    </>
  )
}
